services:
  composer:
    container_name: composer
    image: composer
    working_dir: /var/www/laravel
    command: bash -c "composer self-update && composer install"
    volumes:
      - .:/var/www/laravel
    deploy:
      replicas: 0

  laravel:
    container_name: laravel
    image: php:8.2-fpm-alpine
    networks:
      - laravel
    working_dir: /var/www/laravel
    volumes:
      - .:/var/www/laravel
      - ./.env.production:/.env
    expose:
      - "9000"
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    networks:
      - laravel
    working_dir: /var/www/laravel
    depends_on:
      - laravel
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/laravel/public
      - ./certs:/etc/letsencrypt
    ports:
      - "80:80"
      #- "443:443"
    restart: unless-stopped

  vite:
    container_name: vite
    image: dev:build
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/laravel
    command: bash -c "composer run dev"
    volumes:
      - .:/var/www/laravel
      - ./.env.local:/.env
      - ./server.hmr:/server.hmr
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:5173:5173"
    #deploy:
    #  replicas: 0

networks:
  laravel:
    driver: bridge
